- hosts: k8s
  user: ec2-user
  tasks:
    - name: Build Apps
      shell: |
         git clone https://github.com/fmaulana240699/Automation.git
         python3 build.py
      register: msg
    - debug: var=msg.stdout_lines
