- hosts: k8s
  user: ec2-user
  tasks:
    - name: Build Apps
      shell: |
        git clone https://github.com/fmaulana240699/Automation.git
        cd Automation
        kubectl create -f deployment.yaml
        kubectl create -f services.yaml
