- hosts: k8s
  user: ec2-user
  vars:
    IMAGE_NUM: "{{ IMAGE_NUM }}"          
  tasks:
    - name: Build Apps
      shell: |
         rm -rf Automation
         git clone https://github.com/fmaulana240699/Automation.git
         cd Automation
         sed -i '1 i\IMAGE_NUM: '$BUILD_NUMBER test.py
         python3 test.py
      register: msg
    - debug: var=msg.stdout_lines
