- hosts: k8s
  user: ec2-user
  tasks:
    - name: copy variable
      copy:
        src: variable
        dest: /home/ec2-user/variable
    - name: import variable
      include_vars:
        file: variable
        name: test
    - name: Build Apps
      shell: |
         git clone https://github.com/fmaulana240699/Automation.git
         cd Automation
         export fmaulana="{{test.BUILD_NUMBER}}"
         python3 test.py
      register: msg
    - debug: var=msg.stdout_lines
